pipeline:
  identifier: Build_chloevu_lloyds_harness_test_repo_1741077611656
  name: Build harness-test-repo
  orgIdentifier: default
  projectIdentifier: corebot
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: chloevu-lloyds/harness-test-repo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
